#lang sicp
(define (f g) (g 2))

(define (square x) (* x x))

(f square)

(f (lambda (z) (* z (+ z 1))))

; Here's the process generated by trying to evaluate (f f)
; (f f)
; (f 2)
; (2 2)
; -> Some error complaining that 2 does not name a procedure
