#lang sicp
(define (equal? x y)
  (cond ((and (null? x) (null? y))
         true)
        ((and (list? x) (list? y))
         (and (equal? (car x) (car y))
              (equal? (cdr x) (cdr y))))
        ((and (symbol? x) (symbol? y))
         (eq? x y))
        ((and (number? x) (number? y))
         (eq? x y))
        (else false)))

(define (test x y truth)
  (if (eq? (equal? x y) truth)
      (display 'ok)
      (display 'ERROR))
  (newline))

(test '(this is a list)
      '(this is a list)
      true)
(test '(this is a list)
      '(this (is a) list)
      false)
(test 'a '(a) false)
(test 'a 'a true)
(test '(1 (2 (3 4)))
      '(1 (2 (3 4)))
      true)
(test '(1 (2 3 4))
      '(1 (2 (3 4)))
      false)
